version: 2
jobs:
  build:
    docker:
      - image: maven:3-jdk-11
      - image: circleci/postgres:11.5-alpine-ram

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      TEST_DATABASE_URL: postgresql://postgres@localhost/circle_test

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Setup the database
      - run: apt-get install wget ca-certificates
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
      - run: sh -c 'echo "deb [trusted=yes] http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
      - run: apt-get update
      - run: apt-get -y install postgresql-client-11
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "SELECT * from test"

      - run:
          name: Get dependencies for Maven project
          command: |
            mvn dependency:go-offline

      # Setup firefox and webdriver
      - run: firefox --version
      - run: apt-get install libpango1.0-0
      - run: apt-get -y install firefox
      - run: wget https://github.com/mozilla/geckodriver/releases/download/v0.25.0/geckodriver-v0.25.0-linux64.tar.gz
      - run: tar xzf geckodriver-v0.25.0-linux64.tar.gz
      - run: mv geckodriver /usr/bin/geckodriver

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: |
            mvn compile

      - run: mkdir test-reports

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.9.1.jar

      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.1.jar -log test-reports/selenium.log
          background: true

  test:
    docker:
      - image: maven:3-jdk-11
      - image: circleci/postgres:11.5-alpine-ram

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Get dependencies for Maven project
          command: |
            mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Test
          command: |
            mvn test

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test